// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ai_agent.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_ai_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_ai_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_ai_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_ai_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ai_agent_proto protoreflect.FileDescriptor

const file_ai_agent_proto_rawDesc = "" +
	"\n" +
	"\x0eai_agent.proto\x12\x1astreamlit_and_agent_sdk_go\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2j\n" +
	"\aAIAgent\x12_\n" +
	"\bSayHello\x12(.streamlit_and_agent_sdk_go.HelloRequest\x1a).streamlit_and_agent_sdk_go.HelloResponseBTZRgithub.com/xiao1203/streamlit_and_agent_sdk_go/go_backend/proto_files;proto_files b\x06proto3"

var (
	file_ai_agent_proto_rawDescOnce sync.Once
	file_ai_agent_proto_rawDescData []byte
)

func file_ai_agent_proto_rawDescGZIP() []byte {
	file_ai_agent_proto_rawDescOnce.Do(func() {
		file_ai_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_agent_proto_rawDesc), len(file_ai_agent_proto_rawDesc)))
	})
	return file_ai_agent_proto_rawDescData
}

var file_ai_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_agent_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: streamlit_and_agent_sdk_go.HelloRequest
	(*HelloResponse)(nil), // 1: streamlit_and_agent_sdk_go.HelloResponse
}
var file_ai_agent_proto_depIdxs = []int32{
	0, // 0: streamlit_and_agent_sdk_go.AIAgent.SayHello:input_type -> streamlit_and_agent_sdk_go.HelloRequest
	1, // 1: streamlit_and_agent_sdk_go.AIAgent.SayHello:output_type -> streamlit_and_agent_sdk_go.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_agent_proto_init() }
func file_ai_agent_proto_init() {
	if File_ai_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_agent_proto_rawDesc), len(file_ai_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_agent_proto_goTypes,
		DependencyIndexes: file_ai_agent_proto_depIdxs,
		MessageInfos:      file_ai_agent_proto_msgTypes,
	}.Build()
	File_ai_agent_proto = out.File
	file_ai_agent_proto_goTypes = nil
	file_ai_agent_proto_depIdxs = nil
}
