# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i_agent.proto\x12\x1astreamlit_and_agent_sdk_go\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2j\n\x07\x41IAgent\x12_\n\x08SayHello\x12(.streamlit_and_agent_sdk_go.HelloRequest\x1a).streamlit_and_agent_sdk_go.HelloResponseBTZRgithub.com/xiao1203/streamlit_and_agent_sdk_go/go_backend/proto_files;proto_files b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/xiao1203/streamlit_and_agent_sdk_go/go_backend/proto_files;proto_files '
  _globals['_HELLOREQUEST']._serialized_start=46
  _globals['_HELLOREQUEST']._serialized_end=74
  _globals['_HELLORESPONSE']._serialized_start=76
  _globals['_HELLORESPONSE']._serialized_end=108
  _globals['_AIAGENT']._serialized_start=110
  _globals['_AIAGENT']._serialized_end=216
# @@protoc_insertion_point(module_scope)
